[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc"

[dependencies]
anyhow = "1.0.93"
nohash-hasher = "0.2.0"
rayon = "1.10.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "day1"
harness = false
